<?php

return [
    'ar' => [
        'name' => 'الاسم',
        'username' => 'اسم المُستخدم',
        'email' => 'البريد الالكتروني',
        'pin_code' => 'كود التفعيل',
        'first_name' => 'الاسم الأول',
        'last_name' => 'اسم العائلة',
        'password' => 'الرقم السرى',
        'old-password' => 'الرقم السرى الحالى',
        'password_confirmation' => 'تأكيد الرقم السر',
        'city' => ' حقل المدينة',
        'country' => 'حقل الدولة',
        'address' => 'عنوان السكن',
        'phone' => 'الهاتف',
        'mobile' => 'الجوال',
        'age' => 'العمر',
        'sex' => 'الجنس',
        'gender' => 'النوع',
        'title' => 'العنوان',
        'content' => 'المُحتوى',
        'description' => 'الوصف',
        'excerpt' => 'المُلخص',
        'date' => 'التاريخ',
        'time' => 'الوقت',
        'city_id' => ' المدينة',
        'photo' => '  الصورة',
        'rate' => ' التقييم',
        'state_id' => ' المنطقة',
        'street' => ' الشارع',
        'block' => ' رقم القطعة',
        'building' => ' المبني',        
        'user_mobile' => 'رقم الهاتف',
        'user_name' => 'الاسم',
        'user_id' => 'العميل',
        'package' => 'الباقة',
        'country_id' => 'الدولة',
        'price_id' => 'السعر',
        'gada' => 'الجاده',
        'package_prices.*.subscribe_duration_desc.en' => 'وصف المدة بالإنجليزي',
        'package_prices.*.subscribe_duration_desc.ar' => 'وصف المدة بالعربي',
    ],
];
